# Base Python image
FROM python:3.8-slim-buster

# Update package management
RUN apt-get update \
    && apt-get install -y --no-install-recommends git vim bash-completion curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install dbt completion script
RUN curl https://raw.githubusercontent.com/fishtown-analytics/dbt-completion.bash/master/dbt-completion.bash > ~/.dbt-completion.bash
RUN /bin/bash -c "source ~/.dbt-completion.bash"
RUN echo 'source ~/.dbt-completion.bash' >> ~/.bashrc

# Copy in required files
COPY requirements.txt ./

## Install Python Requirements
RUN pip install -U pip
RUN pip install -r requirements.txt

# Add refresh command
RUN echo 'alias dbt_refresh="dbt clean ; dbt deps ; dbt seed"' >> ~/.bashrc

WORKDIR /home

# Change default profiles.yml location (needs this exact name)
ENV DBT_PROFILES_DIR=/home/profile/

ENTRYPOINT ["dbt"]
