name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Push dbt-dev Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          github-token: ${{ secrets.REGISTRY_TOKEN }}


