name: Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'docker/dbt/**'

jobs:
  docker:
    name: Push dbt-dev Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dbt version
        run: echo "DBT_VERSION=`grep docker/dbt/requirements.txt -e 'dbt-snowflake' | cut -c 16-`" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/dbt/Dockerfile.dev
          tags: ghcr.io/${{ github.repository }}/dbt:${{ env.DBT_VERSION }}
          push: true
